language: node_js
env:
- PORT=8080
node_js:
- node
addons:
  chrome: stable
  firefox: latest
services:
- xvfb
before_script:
- sudo iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-ports 8080
- sudo iptables -t nat -I OUTPUT -p tcp -d 127.0.0.1 --dport 80 -j REDIRECT --to-ports
  8080
- sudo iptables -t nat -L
- npm install -g npm@latest
- npm install
- npm audit fix
- npm install -g chromedriver --chromedriver-force-download --detect_chromedriver_version
- npm install -g mocha@latest
- npm install -g c8@latest
- sleep 3
script:
- c8 npm run All-tests
after_success: c8 report --reporter=html --reporter=text-lcov | coveralls
deploy:
  provider: heroku
  api_key: 02f7c972-ef15-4eb0-8755-4bb89fa337d9
  app: gayole-web
  on:
    repo: fierfeu/Gayole
