language : node_js

env :
    - PORT = 8080

node_js : 
   - "lts/*"

before_script :
    - "sudo iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-ports 8080"
    - "$PORT = 8080"

deploy :
  provider : heroku
  app : gayole-web
  api_key :
    secure : 8d89dec2-5d46-456c-b3d5-217e22765dce
