language : node_js

env :
    - PORT=8080

node_js : 
   - "lts/*"

before_script :
    - npm update
    #- npm audit fix
    - "sudo iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-ports 8080"
    - "sudo iptables -t nat -I OUTPUT -p tcp -d 127.0.0.1 --dport 80 -j REDIRECT --to-ports 8080"
    - "sudo iptables -t nat -L"
    - "export PORT=8080"
    - export DISPLAY=:99.0
    #- sh -e /etc/init.d/xvfb start
    #- npm install -g protractor
    - ./node_modules/protractor/bin/webdriver-manager update --firefox:60.0.2
    #- webdriver-manager update

script :
    - npm run server-test
    - xvfb-run npm run client-test
    - xvfb-run npm run e2e-test

deploy :
  provider : heroku
  app : gayole-web
  api_key :
    secure : 8d89dec2-5d46-456c-b3d5-217e22765dce
