version: 0.2

env: 
  variables:
    PORT: 8080

phases:
  install:
    commands:
      - yum install chromium
      - npm install chromedriver --chromedriver-force-download --detect_chromedriver-version
      - npm install -g mocha@latest
      - npm install -g c8@latest
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - c8 npm run tests-alive
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - src/**/*
    - package.json
    - node_modules/**/*